server:
  port: 8040
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.limir.notification.kafka.order.OrderConfirmation, paymentConfirmation:com.limir.notification.kafka.payment.PaymentConfirmation
  data:
    mongodb:
      username: limir
      password: limir
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  mail:
    host: localhost
    port: 1025
    username: limir
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
