server:
  port: 8070
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    customer-url: http://localhost8222/api/v1/customers
    payment-url: http://localhost8222/api/v1/payment
    product-url: http://localhost8222/api/v1/products